org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.233
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=gothenings_not_yet_eat_all
mod_name=Gothening\u7684\u4e00\u952e\u8fdb\u98df
mod_version=0.1.0
mod_license=MIT
mod_authors=Gothening
mod_description=Press a key to request automatic eating from accessible food storage.
